version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      USE_POSTGRES: "False"
    networks:
      - proyectoanasisdatos_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nombre_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - proyectoanasisdatos_network

networks:
  proyectoanasisdatos_network:
    driver: bridge

volumes:
  pgdata:
